// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIOOPLTswGh_aCQCKGRPjOJ9XToxTemnI',
    appId: '1:1053608780921:web:14d7e4a8009cb597cc20a8',
    messagingSenderId: '1053608780921',
    projectId: 'boomarang-ac130',
    authDomain: 'boomarang-ac130.firebaseapp.com',
    storageBucket: 'boomarang-ac130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP1dWQpHn1g4eTP6liNU5Gv0SssegLSdU',
    appId: '1:1053608780921:ios:9c5fee9fec2304bacc20a8',
    messagingSenderId: '1053608780921',
    projectId: 'boomarang-ac130',
    storageBucket: 'boomarang-ac130.appspot.com',
    iosBundleId: 'com.example.boomarang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP1dWQpHn1g4eTP6liNU5Gv0SssegLSdU',
    appId: '1:1053608780921:ios:02bc67a1b93d071dcc20a8',
    messagingSenderId: '1053608780921',
    projectId: 'boomarang-ac130',
    storageBucket: 'boomarang-ac130.appspot.com',
    iosBundleId: 'com.example.boomarang.RunnerTests',
  );
}
